services:
  postgres:
    image: postgres:16-alpine
    container_name: dni-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-dni_api}
      POSTGRES_USER: ${POSTGRES_USER:-dni}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dni_password}
    volumes:
      - dni_postgres_data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/001-schema.sql:ro
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    container_name: dni-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - dni_redis_data:/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: dni-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "8082:80"
    depends_on:
      - postgres

  api:
    build: .
    container_name: dni-api
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    ports:
      - "8002:8000"

volumes:
  dni_postgres_data:
  dni_redis_data:
